### ISSUE TITLE
Set display order of life events in landing page

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1823] opened 2024-09-18 15:20 UTC
### Description

Set display order of life events in landing page.

**Comment by diegocob** [comment] 2024-10-02 16:49
@gchi25, this seems to be a duplicate of [#1795](https://github.com/GSA/px-benefit-finder/issues/1795). Could we close this?

**Comment by gchi25** [comment] 2024-10-10 21:20
This work is in USAGov dev site.

**Comment by gchi25** [comment] 2024-10-22 17:07
https://www.usa.gov/benefit-finder

![Image](https://github.com/user-attachments/assets/d258162a-9f5d-44c2-ab02-7dbf4f38cd26)

https://www.usa.gov/es/buscador-beneficios

![Image](https://github.com/user-attachments/assets/a9e7c7d6-45c7-46a5-854d-16fa7bada84b)

**Comment by diegocob** [comment] 2024-10-22 18:10
Checking with Ernie to confirm the order that he would like. Proposed:

1. Disability (top left on desktop)
2. DOLO (top right on desktop)
3. Retirement (bottom left on desktop)
4. All-benefits (bottom right on desktop)

**Comment by diegocob** [comment] 2024-10-23 16:49
Ernie confirmed the above order. @gchi25  will test in Main and Prod.

**Comment by gchi25** [comment] 2024-10-24 16:55
The display order is in prod.

![image](https://github.com/user-attachments/assets/e045582c-2b01-4f5b-a1d0-d6bcd489bf5e)

![image](https://github.com/user-attachments/assets/83b7d1f5-41d7-4a7d-aaab-6d3d9faa93f9)

**Comment by diegocob** [comment] 2024-10-24 17:00
Thanks, Gene. Just QA'd it manually on cms.usa.gov/benfit-finder. Lgtm!

**Closed** 2024-10-24 17:47 UTC
