### ISSUE TITLE
Benefit Finder Re-design Style Guide for English Desktop

### ISSUE THREAD

**Issue by ErnestoFernandezAlvarez** [GSA/px-benefit-finder#1461] opened 2024-06-20 15:53 UTC
### Description

I'm creating this ticket to capture the work of the USA.gov BF Redesign Style Guide for Desktop English. 

### User Story

Devs and team need a style guide to help with the development of the new design of the Benefit Finder.

### Acceptance Criteria

- [ ] 1. Angelina/a11y reviews and approves for accessibility. Angelina to also review with a11y USAGov
- [ ] 2. Completed style guide is shared to USAGov UX for review.
- [ ] 3. When USAGov UX team approves via email and no more changes are needed, this task will be done.

This ticket will stay open until completed.
@EnriqueOrt @angelina-smith for viz

Related #991

**Comment by ErnestoFernandezAlvarez** [comment] 2024-06-24 14:34
Here is the Figma file in progress (currently working on typography scales)
https://www.figma.com/design/xij2PUZTouE6cco8f1F2Bn/USAgov-ReDesign-Benefit-Finder?node-id=328-552&t=B4C9WXNSFaJWTYqK-1
<img width="1054" alt="Screenshot 2024-06-24 at 9 32 50 AM" src="https://github.com/GSA/px-benefit-finder/assets/125310691/9f5d099b-5559-4f03-880d-988b5c498420">

**Comment by ErnestoFernandezAlvarez** [comment] 2024-06-26 15:42
Note:
I am doing some of the screen designs as I move forward with this task, in order to see the components in the page.

**Comment by ErnestoFernandezAlvarez** [comment] 2024-06-26 15:45
Here is the progress as of today 6.26.24:
<img width="1144" alt="Screenshot 2024-06-26 at 10 44 37 AM" src="https://github.com/GSA/px-benefit-finder/assets/125310691/fc8b71dd-55b0-4b1e-81cc-4b2e1c7d8b89">

**Comment by ErnestoFernandezAlvarez** [comment] 2024-07-01 17:41
@fongcindy @gscottqueen 
Note on today's date we changed the combo boxes according to client's direction:
-All corners are sharp
-Arrow style as per USWDS component
-The style of the the drop down menu will also change from current (gray background list) to white with black lines, to keep consistency with usa.gov
-We will keep the current Hover state outline style in Teal (as current style)

<img width="1417" alt="Screenshot 2024-07-01 at 12 36 25 PM" src="https://github.com/GSA/px-benefit-finder/assets/125310691/76452323-a472-4845-8f1a-0e86ab337da1">

**Comment by ErnestoFernandezAlvarez** [comment] 2024-07-02 21:32
I am waiting on a few answers from USA.gov for these buttons:

![Image](https://github.com/GSA/px-benefit-finder/assets/125310691/0d7e131d-7d6a-4e26-96dd-4c22275b7ee2)
https://www.figma.com/design/xij2PUZTouE6cco8f1F2Bn/USAgov-ReDesign-Benefit-Finder?node-id=328-552&t=p7B3uAgjiIXASQgk-1

**Comment by fongcindy** [comment] 2024-07-10 15:38
Planning to review with UX team on 7/15, and reviewing with USAGov UX on 7/16

**Comment by ErnestoFernandezAlvarez** [comment] 2024-07-12 19:07
This is the finished style guide to present to USA.gov on 7/16.
@fongcindy this has been revised by Angelina. Also, we discussed error handling with Scott and Angelina. The error design follows Usa.gov's model as close as we can build it.

![Image](https://github.com/user-attachments/assets/a63fa899-a976-4ac1-b8c5-9e88f61cb502)

**Comment by fongcindy** [comment] 2024-07-24 15:48
Received USAGov UX and a11y comments on 7/24. Will be reviewing feedback and discuss what changes we will or will not incorporate.

**Comment by ErnestoFernandezAlvarez** [comment] 2024-07-29 14:45
Hello Team
@fongcindy @angelina-smith @gscottqueen
We handed off partial style guide to the Dev team on July 26th, as discussed with Ernie and team:

- Color
- Combo Boxes
- Buttons
- Summary Box

Here is the link to the [Figma Dev page](https://www.figma.com/design/xij2PUZTouE6cco8f1F2Bn/USAgov-ReDesign-Benefit-Finder?node-id=1033-1171&t=9Ii0XPwc0POOjDpU-1) + Screenshot attached

Next Steps:
I am continuing with updates following Client, Devs and Accessibility comments + re-iterating error handling flow.



![Image](https://github.com/user-attachments/assets/00771e9c-9b3a-4dfb-84ba-24544cf1afd1)

**Comment by fongcindy** [comment] 2024-08-09 21:28
Meet with USAGov UX on 8/7, confirmed we are good to go with what we currently have. 
Changes that are captured include: colors, buttons, error handling. 

Items like type scale will be backlogged and will revisit once USAGov informs us of exact specifications of typography. 

Closing this ticket because USAGov has approved verbally during the redesign sync on 8/7

**Closed by fongcindy** 2024-08-09 21:28 UTC
