### ISSUE TITLE
QA | Data Analytics v.04.0.

### ISSUE THREAD

**Issue by EnriqueOrt** [GSA/px-benefit-finder#1379] opened 2024-05-29 17:30 UTC
### Domain

data

### Related Issue(s)

[Data Layer Value stale on new view](https://github.com/GSA/px-benefit-finder/issues/1334)	https://github.com/GSA/px-benefit-finder/issues/1334
[Test Datalayer push event](https://github.com/GSA/px-benefit-finder/issues/1318)	https://github.com/GSA/px-benefit-finder/issues/1318

Due on June 5th - pending kickoff confirmation 

### Description

Data Analytics final QA for data reporting related updates

**Comment by scottqueen-bixal** [comment] 2024-05-29 17:37
closing as complete

**Comment by EnriqueOrt** [comment] 2024-06-03 19:05
Hey @nickpistone - do you have any updates on this work? Could you make sure it is completed no later than the 5th of June? 

@fongcindy for vis

**Comment by nickpistone** [comment] 2024-06-05 16:14
I also left comments under #1318. I can confirm that the data layer attributes are showing up in GTM preview. I was expecting them to be associated with the bf_page_change event, but instead they are associated with the bf_count event. I don't think that's an issue, but just mentioning it.

**Closed** 2024-06-05 16:14 UTC

**Comment by nickpistone** [comment] 2024-06-06 16:28
After additional testing, I think the "datalayer stale" issue is resolved since it does update when you submit new results. By using the bf_count custom event to trigger the eligible, more info, and not eligible variables, then we should be able to get accurate results since every time that event fires, it updates the values.
