### ISSUE TITLE
Update content capitalization

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-benefit-finder#819] opened 2024-01-23 22:16 UTC
On all benefit finder start pages: Review Results -> Review results

On all benefit finder form page 1: Marital Status -> Marital status

**Comment by diegocob** [comment] 2024-01-25 17:10
There's a few of these capitalizations which are not editable on CMS. 

This needs to be done from the dev side, pingin @scottqueen-bixal to let us know how to proceed.

Nancy pointed some of these out also. For example:
-> Required fields: DOB (r~~R~~iquired)
-> Review r~~R~~esults
-> Review and c~~C~~onfirm

**Comment by diegocob** [comment] 2024-01-29 22:33
Should I create separate tickets for these or will this ticket be enough, @scottqueen-bixal?

**Comment by scottqueen-bixal** [comment] 2024-02-06 16:40
> Should I create separate tickets for these or will this ticket be enough, [@scottqueen-bixal](https://github.com/scottqueen-bixal)?

this is good @diegocob

**Comment by diegocob** [comment] 2024-02-09 17:41
There is another capitalization in the accordions:
Change `Likely Eligible` to `Likely eligible`
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/dc3dc2e4-59c5-4d52-9dde-832501d5d0b8)

**Comment by scottqueen-bixal** [comment] 2024-02-12 17:16
These is a collection of the requested content capitalization changes requested for items in the UI content from this ticket

- On all benefit finder start pages: Review Results -> Review results
- On all benefit finder form page 1: Marital Status -> Marital status
- Required fields: DOB (r~R~iquired)
- Review r~R~esults
- Review and c~C~onfirm
- Change Likely Eligible to Likely eligible

**Comment by scottqueen-bixal** [comment] 2024-02-12 17:28
`On all benefit finder form page 1: Marital Status -> Marital status`, is not a UI content update.  Looks like it comes from the form. Can you confirm?



![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/e8ab34ea-c8ce-4464-8ba2-8310516428d9)



There are other cases in our eligibility labels, do any of these other items need to be updated?

`Change Likely Eligible to Likely eligible`

```JSON
      "eligibleStatusLabels": [
        "Likely eligible",
        "More Information Needed",
        "Not Eligible"
      ],
```

**Comment by diegocob** [comment] 2024-02-12 19:05
Right. The `Marital Status` is a content-related item.

The `(Required)` is a UI/static one.

> `On all benefit finder form page 1: Marital Status -> Marital status`, is not a UI content update. Looks like it comes from the form. Can you confirm?
> 
> ![Image](https://private-user-images.githubusercontent.com/37077057/304171201-e8ab34ea-c8ce-4464-8ba2-8310516428d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjQ5MTcsIm5iZiI6MTcwNzc2NDYxNywicGF0aCI6Ii8zNzA3NzA1Ny8zMDQxNzEyMDEtZThhYjM0ZWEtYzhjZS00NDY0LThiYTItODMxMDUxNjQyOGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE5MDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZmNmNTA3ZWI2MDA5ZGQ1MGQxNjdiMjdjZDA5YTNiODg0MThjMjRhMTUwNmUyM2FlYjllOTg2OTlkYjJiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6FPy9vDsQvLexH7AChBlME-QgOaQ1JP9oZ_WPkGvuSw)
> 
> There are other cases in our eligibility labels, do any of these other items need to be updated?
> 
> `Change Likely Eligible to Likely eligible`
> 
> ```json
>       "eligibleStatusLabels": [
>         "Likely eligible",
>         "More Information Needed",
>         "Not Eligible"
>       ],
> ```

**Comment by scottqueen-bixal** [comment] 2024-02-12 19:11
thanks for the update @diegocob , still need confirmation on the other eligible status labels, this is low priority so moving to blocked until update is confirmed when you return.

**Comment by diegocob** [comment] 2024-02-14 16:53
Hi @scottqueen-bixal,
Confirming these other labels also need to be updated to sentence case:
   "Likely eligible",
        "More i~I~nformation n~N~eeded",
        "Not e~E~ligible"

**Comment by diegocob** [comment] 2024-02-14 18:19
Adding an item to this list:
- On all benefit finder start pages: Review Results -> Review results
- On all benefit finder form page 1: Marital Status -> Marital status
- Required fields: DOB (rRiquired)
- Review rResults
- Review and cConfirm
- Change Likely Eligible to Likely eligible
- **On top of pg1 change "Complete Questions" --> "Answer these questions"**



![Image](https://github.com/GSA/px-benefit-finder/assets/125094772/3f11f061-be13-4848-b06a-e78839c78a37)

**Comment by diegocob** [comment] 2024-02-16 19:42
Adding yet another item to this list (don't want to make it too long but fits in the same category):

1. On all benefit finder start pages: Review Results -> Review results
2. On all benefit finder form page 1: Marital Status -> Marital status
3. Required fields: (Required) -> (required)
**4. Spanished required fields: (Se requiere) -> (requerido)** 
5. End of form modal: Review Results -> Review rResults
6. Review and Confirm -> Review and confirm
7. Likely Eligible -> Likely eligible
8. On top of pg1 change "Complete Questions" --> "Answer these questions"
![Image](https://github.com/GSA/px-benefit-finder/assets/125094772/2fe019c2-815c-4e7a-a2df-ef0e6ba58abb)

**Comment by EnriqueOrt** [comment] 2024-02-20 18:50
@diegocob - let's pri and complete all capitalization mentioned on this ticket - All changes should be able to be complete at content level. 

On all benefit finder start pages: Review Results -> Review results
On all benefit finder form page 1: Marital Status -> Marital status
Required fields: DOB (rRiquired)
Review rResults
Review and cConfirm
Change Likely Eligible to Likely eligible

**Comment by scottqueen-bixal** [comment] 2024-02-21 14:15
Hey Diego, use this branch https://github.com/GSA/px-benefit-finder/pull/892 for additional changes to [Update content capitalization #819](https://github.com/GSA/px-benefit-finder/issues/819).
![Screenshot 2024-02-21 091300](https://github.com/GSA/px-benefit-finder/assets/37077057/f495ab29-4c10-4798-86cd-28605ed448ca)

**Comment by diegocob** [comment] 2024-02-21 17:06
Ok, will dig in the branch. Will let you know if I can't find something.

**Closed** 2024-02-29 17:50 UTC

**Comment by diegocob** [comment] 2024-03-08 22:24
## Content QA

Began content QA, TBContinued - Diego

## Related Github Issue

- fixes #819 

## Detailed Testing steps
| Done | Life event  | Comment |
|-------------|--------------------|--------------------|
| ✅   |  DOLO EN | | 
| ✅ |  DOLO SP | | 
| ⚪ |  Disability EN | | 
| ⚪ |  Disability SP | | 
| ⚪ |  Retirement EN | | 
| ⚪ |  Retirement SP | | 
 
## Checking for these changes

| Before | After  | Where |
|-------------|--------------------|--------------------|
| Review Results  | Review results  | Intro page steps |
| Required | required | Adjacent to required fields |
| Review and Confirm | Review and confirm | Verify selections view  heading|
| Likely Eligible | Likely eligible | Items marked in results |
| More Information Needed | More information needed | items marked in results | 
| Not Eligible | Not eligible | Items marked in results |
| Error status | Error | Error message |
| All fields marked required must be completed | Complete all required fields | Error message |
| Complete Questions | Answer these questions | Section headings |
| Final Questions | Questions continued | Section headings |
| Time to complete [2-5 mins] | Estimated time [2-5 mins] | Time indicator, intro page |
| <ul><li>Your information **is not** shared, saved, or submitted. </li><li>Provide complete info to get more relevant results.</li><li>**This form is not an application.** You will need to apply for benefits with each agency.</li></ul> | <ul><li>**This is not an application.** This tool will help you find possible benefits.</li><li>Your answers **are not** saved or submitted.</li><li>**Answer all questions** to get better results.</li></ul> | Before you start bullets, intro page |
| No input given| Not answered | Review your results section |
| Date should follow the format 01 - January 22 1977 | Date should follow the format January 19 2000 | Date error message |

**Spanish**
| Before | After  | Where |
|-------------|--------------------|--------------------|
| Tiempo para completar | Tiempo estimado | Start page |
| <ul><li>Su información **no será** compartida, guardada o presentada.</li><li>Ingrese la información completa para obtener resultados más relevantes.</li><li>**Este formulario no es una aplicación.** Tiene que presentar una solicitud por cada beneficio.</li></ul> | <ul><li>**Esto no es una aplicación.** Este formulario le ayuda a encontrar beneficios.</li><li>Sus respuestas **no serán** guardadas o presentadas.</li><li>Para mejores resultados **responda todas las preguntas**.</li></ul> | Before you start bullets |
| Se requiere | requerido | Required fields |
| Estado de error | Error | Error message
| Todos los campos marcados como obligatorios deben ser completados. | Responda los campos requeridos. | Error message |
| No se ha dado ninguna entrada | No respondió | Review results section |
| Podría calificar para estos beneficios: | Podría ser elegible para estos beneficios: | Results sections | 
| Preguntas completas | Responda las preguntas | Page 1 section heading |
| Preguntas Continuación | Preguntas continuadas | Page 2 section heading | 
| La fecha debe seguir el formato 01 - 22 de enero de 1977. | Use el formato enero 19 2000 | Wrong date error message |

**Comment by diegocob** [comment] 2024-03-11 23:42
Hi Scott, I need to make an edit to the disclaimer bullets the intro page in SP - for readability. It's good as it is but will read better with "Este formulario le ayudará a encontrar beneficios."

Where would you prefer me to do them? 
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/90726bba-1316-4281-8848-257fb578c548)

**Comment by diegocob** [comment] 2024-03-12 22:38
QA is done. Need to make the changes in the comment above.
